### ISSUE TITLE
reference member is initialized to a temporary that doesn't persist after the constructor exits

### ISSUE THREAD

**Issue by paleozogt** [jimmiebergmann/mini-yaml#2]
Older compilers seem to let this slide, but newer compilers (for example clang v8) rightly 
complain about this sort of thing:

```
std::pair<const std::string &, Node &> Iterator::operator *()
{
    switch(m_Type)
    {
    case SequenceType:
        return {"", *(static_cast<SequenceIteratorImp*>(m_pImp)->m_Iterator->second)};
        //      ^---- reference member 'first' binds to a temporary object whose lifetime would be shorter than the lifetime of the constructed object
        break;
    ...  
```

That string literal is going to make a temporary `std::string`, which will destruct when the function returns.  The problem occurs at `Yaml.cpp:720` and `Yaml.cpp:871`.

**Comment by jimmiebergmann** [comment]
Fixed in https://github.com/jimmiebergmann/mini-yaml/commit/22d3dcf5684a11f9c0508c1ad8b3282a1d888319
