### ISSUE TITLE
ConstIterator copy-constructor doesn't initialize members

### ISSUE THREAD

**Issue by paleozogt** [jimmiebergmann/mini-yaml#3]
`ConstIterator`'s copy-constructor doesn't initialize its members.  It calls into `operator=` where things can go haywire, as it can be fooled into calling `delete` on a garbage `m_pImp`.

You may not have seen this problem in your testing due to [copy elision](https://en.cppreference.com/w/cpp/language/copy_elision) in your compiler.  With gcc you can use `-fno-elide-constructors` to turn it off for testing.

**Comment by jimmiebergmann** [comment]
Good catch. Same bug in implementation of Iterator::Iterator(const Iterator & it).

**Comment by jimmiebergmann** [comment]
Fixed in https://github.com/jimmiebergmann/mini-yaml/commit/22d3dcf5684a11f9c0508c1ad8b3282a1d888319
